[package]
name = "athira"
version = "1000.9.0"
edition = "2021"


[dependencies]
clap = { version = "4.4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
thiserror = "1.0"
anyhow = "1.0"
colored = "2.0"
dirs = "5.0"
regex = "1.9"
