[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "athira"
dynamic = ["version"]
description = "Athira CLI tool"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.7"
authors = [
    { name = "Your Name", email = "your.email@example.com" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.hatch.version]
path = "athira/__init__.py"

[tool.hatch.build]
artifacts = [
    "athira/bin/*",
]

[tool.hatch.build.targets.wheel]
packages = ["athira"]
